export type EntityType = [
  | "Item"
  | "Mesh"
  | "Player"
  | "Fireball"
  | "Iceball"
  | "Cow"
  | "Sheep"
  | "Horse"
  | "Cave Golem"
  | "Draugr Zombie"
  | "Draugr Skeleton"
  | "Frost Golem"
  | "Frost Zombie"
  | "Frost Skeleton"
  | "Draugr Knight"
  | "Wolf"
  | "Bear"
  | "Deer"
  | "Stag"
  | "Gold Watermelon Stag"
  | "Gorilla"
  | "Wildcat"
  | "Magma Golem"
  | "Draugr Huntress"
  | "Spirit Golem"
  | "Spirit Wolf"
  | "Spirit Bear"
  | "Spirit Stag"
  | "Spirit Gorilla"
  | "Draugr Warper"
  | "Frost Wraith"
  | "Draugr Reaver"
  | "NPC"
  | string,
];
